### ISSUE TITLE
Escritura científica con LaTeX

### ISSUE THREAD

**Issue by Pakillo** [ecoinfAEET/Notas_Ecosistemas#14]
Liderada por @saizhugo
Fecha de envío estimada: Diciembre 2017

**Comment by ibartomeus** [comment]
Hugo ya ha enviado el primer draft de la siguiente nota ecoinformatica: https://github.com/ecoinfAEET/Notas_Ecosistemas/tree/master/markup

Que empieze el proceso de revisión!

**Comment by ibartomeus** [comment]
Me gusta mucho, algunos commnets: 
linea 11: Para los puristas R no es un software, sino un lenguaje de programación
linea 15: Yo añadiria que una de las ventajas de R es la reproducibilidad. Asi lo atas a las ventajas del  procesado de textos por linea de comandos.
Linea 34: añadir un link a Markdown?
Linea 50. Ecosistemas tiene un template Rmarkdown, lo podrias linkar! @Pakillo te puede dar más datos.







@saizhugo , si quieres que te añada como collaborator y editas directamente este repo, dimelo.

**Comment by saizhugo** [comment]
Sí, de hecho el texto está escrito sobre ese template. Por mí no hay
problema en linkar el template directamente. por otro lado, hazme
colaborador que así será todo más fácil.

¡Cualquier comentario será bienvenido!

**Comment by ajpelu** [comment]
Buenas Hugo, gracias por la contribución. Está genial, me encanta el enfoque que le has dado, y especialmente la idea final, de no perdernos tanto en el "cómo" sino en el "qué". 

Solamente algunos comentarios sencillos (he revisado el documento llamado Ecoinf2.docx): 

- Palabras clave: sustituir "Lenguaje Text" por "Lenguaje TeX". 
- Idem en Keywords: sustituir "Text language" por "TeX language" 
- L25: sustituir "número 1, 2 ..." por "números 1, 2 ..." 
- L31: eliminar "`" al final de la frase
- L33: Latex debería escribirse LaTeX 
- L34: Quizá para citar Rmarkdown, incluiría la cita que nos recomiendan sus autores. Si ejecutas `citation("rmarkdown")` obtienes esto: 
To cite package 'rmarkdown' in publications use:

  JJ Allaire, Joe Cheng, Yihui Xie, Jonathan McPherson, Winston Chang, Jeff Allen, Hadley Wickham, Aron Atkins, Rob Hyndman and Ruben Arslan
  (2017). rmarkdown: Dynamic Documents for R. R package version 1.6. https://CRAN.R-project.org/package=rmarkdown 
- L52: Falta una coma en "páginas etc)". Cambiar por "páginas, etc)" 
- L50-56: ¿Has pensado en hacer alguna mención al repositorio de estilos de bibliografías http://citationstyles.org/? Creo que puede ser interesante indicar que hay un repositorio con las especificaciones de los formatos de bibliografía para muchas revistas. 
- L68: Falta una coma en "comprobar los datos etc" 
- L69: Sugerencia: cambiar "repetir" por "replicar" 

Pues nada, de nuevo, gracias por la contribución. 
AntonioJ

**Comment by Pakillo** [comment]
Hola,

Gracias @saizhugo por la contribución!

He subido mis comentarios al repo (Ecoinf2_FRS.docx). Yo la veo muy bien. Como sugerencia, quizás sería bueno incluir alguna imagen de un fragmento de un Rmarkdown, por que la gente se haga una idea de cómo se escriben ecuaciones, o cómo se actualizan los resultados dinámicamente. Pero tampoco es imprescindible.

Para evitar el doble paréntesis en las citas bibliográficas tienes que incluirlas entre corchetes en lugar de paréntesis (ver http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html).

Gracias de nuevo por la submission!

P
