### ISSUE TITLE
Revisión VegX

### ISSUE THREAD

**Issue by ibartomeus** [ecoinfAEET/Notas_Ecosistemas#19]
El texto aquí: https://github.com/ecoinfAEET/Notas_Ecosistemas/tree/master/VegX

A comentar!

**Comment by ibartomeus** [comment]
Revisión de Hugo Saiz:

Comentarios generales:
- Se me hace repetitivo en el primer párrafo tanto uso de la palabra 'datos' (p.ej. datos en bases de datos). ¿Se podría cambiar alguna vez por otras palabras tipo 'información'?
- Algunos téminos (estándar, estructuras únicas) creo que habría que explicarlos para que sean más accesibles a la gente.
- Me falta una conclusión, tal vez un par de ideas hablando sobre que la colaboración científica y compartir datos son muy necesarios y que estas herramientas son fundamentales para ello.
- ¿Habría hueco para una foto de cómo se ven/introducen los datos en Veg-x? No lo he consultado pero creo que tener una UI bonita/comprensible ayuda mucho a que la gente quiera formar parte de ello.
In line:
- definir "estandard" para no especialistas
- clarificar a que se refiere estructuras únicas

**Comment by ibartomeus** [comment]
Revisón I Bartomeus:

Me gusta mucho la idea y el tono. Yo añadaria tres cosas:

1) Una frase al inicio que refleje el problema tratado claramente, que a mi ver es: Una vez tenemos estandards, necesitamos herramientas para facilitar a la gente su uso. Si no es facil usarlos y no se usan, no sirven para nada. Ahora la intro te va guiando, pero no ves a donde quiere llegar hasta el final. Esta frase inicial actuaria a modo de mini,mini abstract.

2) Un link explicito de como hacerte llegar estos workflows (e.g. a los issues de to github?)

3) Una linea de conclusión que lo ponga en contexto, por ejemplo, los metadatos en EML les paso algo parecido, el standard es muy complicado y por eso no se usa, herramientas como rEML de ropensci intentanm facilitar esa tarea.

Muahca gracias!

**Comment by Pakillo** [comment]
Muchas gracias @miquelcaceres por la nota sobre VegX. Muy interesante!

Yo la veo muy bien pero creo que aún tienes espacio (de momento no llega a 800 palabras) para explicar algo más en la línea de lo que comentan Hugo y Nacho. 

Quizás también añadir un readme al repo de GitHub guiando a los potenciales usuarios del paquete (e.g. con enlaces a las viñetas ya renderizadas). P. ej. pkgdown es buenísimo para eso.

Tras ojear rápidamente los tutoriales del paquete, pienso que tal vez crear una app interactiva para la recogida de los datos (e.g. tipo shiny) puede hacer el proceso menos engorroso para muchos usuarios. Pero entiendo que eso puede salirse de los objetivos del paquete, o suponer demasiado trabajo extra.

Por último, no sé si te has planteado solicitar un review de rOpenSci (https://github.com/ropensci/onboarding) pero seguro que iban a poder aportar buenas sugerencias. Sobre todo después de su experiencia desarrollando el paquete para EML.

He subido un Word con control de cambios a este repo (carpeta VegX) con algunos cambios o sugerencias muy menores. Para la submission a Ecosistemas habría que formatear el Word según las instrucciones de la revista. Si pasas el texto a Rmarkdown según la plantilla que ofrecemos en este repo, el formateo será automático. Si no quieres liarte con Rmarkdown avísanos y nos encargaremos nosotros

Gracias de nuevo por la nota!

Paco

**Comment by miquelcaceres** [comment]
Hola a todos,

Gracias Hugo, Nacho y Paco por la revisión y los comentarios. Me parecen muy útiles. Conozco un poco EML, y estoy de acuerdo que la sencillez es esencial para la adopción de un estandar de intercambio de datos. En nuestro caso, no sé si lo conseguiremos. Ya he hecho caso a Paco en cuanto al readme del paquete y al uso de pkgdown para generar una página de VegX dentro de GitHub. En cuanto a la app con shiny, es una cosa que consideramos al inicio, pero llevará bastante trabajo y por ahora no es una prioridad (primero hay que estabilizar el estandar y el paquete de R). 

Mañana me pongo con la revisión (intentaré hacerlo con la plantilla Rmarkdown) y lo envio a través de la web de Ecosistemas.

Un saludo,
Miquel
