### ISSUE TITLE
Crear un paquete en R

### ISSUE THREAD

**Issue by ibartomeus** [ecoinfAEET/Notas_Ecosistemas#20]
Explicar las ventajas y un manual muy simple usando use_this{} seria genial.

**Comment by ibartomeus** [comment]
@garciacallejas , @marcelinodelacruz os animais a explicar en 1000 palabras como crear un paquete?

**Comment by garciacallejas** [comment]
claro que sí! ahora lo tengo muy a mano

**Comment by marcelinodelacruz** [comment]
¡Por supuesto! Eso, sí: habrá que sudar para ajustarlo a 1000 palabras.

**Comment by marcelinodelacruz** [comment]
David y yo estamos ya trabajando en esta nota. Se puede cambiar la etiqueta a "in preparation"

**Comment by ibartomeus** [comment]
Ya podeis revisar la nota (https://github.com/ecoinfAEET/Notas_Ecosistemas/tree/master/crear_paquetes_R)!

**Comment by ibartomeus** [comment]
@garciacallejas @marcelinodelacruz Revisión completa, mirar los comentarios finales de Paco y mios y podeis enviar a ecosistemas la nota via su pagina web. David, avisame si quieres antes y le doy una última leída editorial.
