### ISSUE TITLE
Introducción a la Estadística Bayesiana: pros y cons

### ISSUE THREAD

**Issue by Pakillo** [ecoinfAEET/Notas_Ecosistemas#21]
Liderada por @ruizbp. Fecha prevista de submission: Mayo-Junio 2018

**Comment by ajpelu** [comment]
Muchas gracias @ruizbp por liderar y escribir esta nota. 

Me ha parecido muy interesante y creo que puede ser útil para los que no sabemos mucho de estadistica bayesiana. He revisado el texto y tengo pequeñas sugerencias. Ahí van: 

- A lo largo del texto aparece "a priori" a veces en cursiva y otras veces no. ¿Están así por algún motivo? En caso de que no, sugiero homogeneizar el formato. 
- También ocurre con "p.ej." que a veces aparece con espacio en blanco y otras veces no. 
- Creo que ayudaría incluir algo mas de información sobre paquetes estadísticos en R. Por ejemplo, hay un Cran Task View sobre bayesiana [https://cran.r-project.org/web/views/Bayesian.html](https://cran.r-project.org/web/views/Bayesian.html) que podría ayudar a la gente que quiere iniciarse en esto. 
- En la línea del comentario anterior, quizá sería interesante incluir una tablita de revisión con principales paquetes con sus limitaciones y/o ventajas. ¿Lo ves factible? 
- Sugiero añadir la cita de los paquetes rstan y brms. 
- Finalmente me parece muy interesante el párrafo final que habla del grupo de Estadística Bayesiana, sin embargo, echo en falta que en la nota apareza alguna forma de contacto específica: página web, lista de correo, etc. 

Muchas gracias @ruizbp por la nota. Me ha parecido muy interesante. 

Abrazos, 

Antonio J.

**Comment by saizhugo** [comment]
Una nota más. Al final parece que la cosa marcha. Gracias por el esfuerzo a los participantes.

Aquí mando mi revisión. Un par de correcciones de texto y algún comentario sobre secciones concretas. Creo que sería interesante incluir en el texto/bibliografía algún manual/tutorial para quien quiera introducirse en el mundo del Bayesiano. Además, me parece que para ser justos sería necesario hablar de los contras de la estadística Bayesiana (se dicen por encima, pero tal vez hay que dejarlos más claros). 

Me gusta mucho el último párrafo para concluir. Ahora, creo que tal vez tengáis que especificar que es un grupo del departamento (entiendo), no sea que os empiecen a llegar solicitudes de todo el mundo para unirse ;)

nos vemos,
Hugo

[NotaEcosistemas_09mayHSaiz.docx](https://github.com/ecoinfAEET/Notas_Ecosistemas/files/1994608/NotaEcosistemas_09mayHSaiz.docx)

**Comment by ruizbp** [comment]
Muchas gracias por las revisiones, las hemos encontrado muy útiles y creemos que han mejorado sustancialmente la nota. Perdonad que hayamos tardado un poco pero he esperado a la siguiente reunión del grupo para discutir un par de cosas. Adjunto os envío la versión revisada y hemos incluido una carta de respuesta ;o) Si tenéis cualquier comentario más a la versión revisada por favor decírmelo y lo incluiremos. Ahora la hemos mandado al departamento para informar, así que si hubiera algún cambio durante esta semana os lo comunicaría.

Muchas gracias, quedamos a la espera de vuestras noticias. Iremos pensando en la siguiente nota con un ejemplo sencillo de estadística Bayesiana usando stan ;o)

Un abrazo y muchas gracias de nuevo!


[Respuestas_R1.docx](https://github.com/ecoinfAEET/Notas_Ecosistemas/files/2030177/Respuestas_R1.docx)
[NotaEcosistemas_23may_R1.docx](https://github.com/ecoinfAEET/Notas_Ecosistemas/files/2030178/NotaEcosistemas_23may_R1.docx)

**Comment by saizhugo** [comment]
Hola Paloma,

menuda revisión. Vamos a tener que establecer revisores certificados para
mirar las notas en profundidad.

A mí me parece que ha emjorado. No tengo nada que decir salvo que en la L74
creo que se os ha coloado un 'la' ("...sobre la cómo...").

Nos vemos
Hugo

**Comment by Pakillo** [comment]
Gracias Paloma et al por esta magnífica nota. Me ha gustado mucho. He hecho algunos comentarios y sugerencias en el Word adjunto

Ojalá esas reuniones de EcoBayes nos pillaran más cerca! :)

[NotaEcosistemas_23may_R1_FRS.docx](https://github.com/ecoinfAEET/Notas_Ecosistemas/files/2030694/NotaEcosistemas_23may_R1_FRS.docx)

Mantendremos la revisión abierta hasta final de mes (31 de Mayo)

**Comment by ibartomeus** [comment]
Si nadie tiene nada más que añadir, yo la daria por buena y podeis enviarla a la https://www.revistaecosistemas.net/ como "nota ecoinformatica". Saldra en el numero de Julio-Agosto.

Gracias!
