### ISSUE TITLE
Cómo compartir datos y código asociados a publicaciones

### ISSUE THREAD

**Issue by Pakillo** [ecoinfAEET/Notas_Ecosistemas#23]
Repositorios, DOIs, metadatos etc.
Posibilidad de hacer una nota única, o probablemente mejor, separar datos y código. Yo podría liderar la de código, y creo que @ajpelu podría escribir la de datos no?

**Comment by ajpelu** [comment]
Hooola, me parece genial! Cuenta conmigo @Pakillo, pero dejame margen que ando liado. Hacemos una conjunta o dos separadas?

**Comment by Pakillo** [comment]
Yo creo que mejor separadas. P.ej. la de datos, sólo con describir los repositorios principales y cómo estructurar los meta datos ya va sobrado... Te dejo eso a ti vale? Sin prisas. Y yo escribo la de código

**Comment by SaraVarela** [comment]
Hola @Pakillo estaba pensando ponerme un poco al día en esto de compartir proyectos de R, y ya de paso que me pongo, escribir una nota sobre cómo usar docker. Es compatible con lo que estás preparando? solapa? a parte? ya me dirás! abrazo grande

**Comment by Pakillo** [comment]
Gracias Sara. No solapa nada :) No pensaba meterme en Docker. Eso da para una nota en sí misma ;-)

Por cierto que han salido unos cuantos paquetes de R que facilitan el uso de Docker: liftr, containerit, stevedore, dockerfiler...

Looking forward to reading your note!

**Comment by ajpelu** [comment]
Hola @Pakillo estamos trabajando una compañera y yo la nota de compartir datos. La semana que viene la tendremos acabada (creo), ¿te animas a participar?

**Comment by Pakillo** [comment]
Qué bien! Mándala cuando la tengáis lista y, si veo que puedo contribuir, lo haré

**Comment by ajpelu** [comment]
Buenas tardes compañeros, aunque con restraso, os enviamos nuestra propuesta de nota sobre compartir datos. Hemos estado trabajando en ella @AndreaRC y un servidor. Os adjuntamos el word que hemos preparado. ¿@Pakillo @ibartomeus decidnos si vale así o lo mandamos de otra forma? [PerezLuque_RosCandeira_datapapers.docx](https://github.com/ecoinfAEET/Notas_Ecosistemas/files/3112365/PerezLuque_RosCandeira_datapapers.docx) 

Muchas gracias. Abrazos enormes

**Comment by ibartomeus** [comment]
Lo ideal es subirlo a una carpeta (en Rmd?) en el repo de git, asi la gente puede comentar allí, pero veo que solo el texto principal son 2700 palabras. Las Notas no deberial parar de 1000-1500 y 1-2 figuras. Una opción es que lo recorteis, otra opción es que lo envieis como articulo completo a la revista. Como prefirais.

Por cierto, muy chulo!

**Comment by ajpelu** [comment]
Gracias @ibartomeus 

Ok, ahora lo hacemos (creamos la carpeta y subimos el Rmd?)  Vamos a intentar recortar la nota, aunque no se si nos merece la pena enviarlo como artículo. Le pregunto a @AndreaRosC y os digo. Gracias

**Comment by ajpelu** [comment]
Buenas de nuevo @ibartomeus y @Pakillo 

Acabamos de hacer un pull request con la nota que hemos creado y la hemos incluido en la carpeta llamada compartir_datos. Está todo el material (Rmd y demás) así como un archivo en word con la nota montada. 

@AndreaRosC y yo estamos de acuerdo respecto a lo que comentas @ibartomeus de las figuras y del tamaño de la nota. Podríamos eliminar una figura (quizá la primera), pero en cuanto a recortar, hemos intentado ser lo más escuetos posibles. Valorando lo que nos propones, nos surgen un par de dudas: 
- Consideramos que es una nota (un poco larga) con contenido Ecoinformático y por ello pensamos que encaja bien en esta sección. 
- Si la enviamos como articulo de revisión o similar a Ecosistemas, ¿perderíamos el proceso de revisión abierta por la comunidad? Esto creemos que puede ser importante, y no nos gustaría perderlo. 
- Por otro lado, podemos intentar acortar un poco, pero creo que podamos llegar a 1500 palabras. 

¿alguna sugerencia / consejo? @Pakillo @ibartomeus 

Gracias, 

buen día

**Comment by ajpelu** [comment]
Buenas tardes, finalmente esta nota se nos hizo demasiado grande y se va a publicar en el próximo número de Ecosistemas como Artículo de Revisión. 
Muchas gracias 
Un saludo
