### ISSUE TITLE
Revisión Github para ecologos

### ISSUE THREAD

**Issue by ibartomeus** [ecoinfAEET/Notas_Ecosistemas#28]
Podeis comentar hasta finales de Junio: https://github.com/ecoinfAEET/Notas_Ecosistemas/tree/master/GitHub_para_Ecologos

**Comment by algarsal** [comment]
Hola Javier (te lo vuelvo a enviar por aquí).

Me gusta mucho tu nota de git y github. Yo añadiría al menos alguna referencia a otros servidores como gitlab y bitbucket (yo es el que más uso). Estos dos permiten proyectos privados. El proceso es en todos ellos muy parecido.

Se me ha hecho extraño el planteamiento de empezar por github en vez de por git. Yo utilizo git en el ordenador como control de versiones (con gitcola) y sólo en algunos proyectos utilizo bitbucket para tener el repositorio en la red. Sobre todo los proyectos de R (con Rstudio) que pesan poco. Github lo veo más para colaborar que sólo control de versiones. 


Es sólo una sugerencia, la nota la veo fenomenal en cualquier caso.

Saludos

Alfonso

**Comment by farcego** [comment]
Buenas!
Yo tambien hecho un poco en falta una separacion mas clara de lo que es git y github, git para trabajar en local y GitHub para compartir/colaborar (Git seria el motor de github, github solventa el tener que crear-gestionar servidores compartidos para almacenar las versiones, y ademas tiene una interfaz de usuario bastante amigable).
Tambien se deberia? mencionar de algun modo el beneficio social de usar GitHub (a diferencia de solo git)? Estoy seguro de no ser ni mucho menos el unico que ha encontrado codigo util siguiendo / buceando en los repos de otros investigadores, y ha abierto alguna colaboracion con gente que esta haciendo codigo en temas no muy diferentes. Y lo mismo para el uso de ciertas funciones, maneras de optimizar codigo etc... Tambien permite estar al dia de las acutalizaciones de nuestros paquetes preferidos... Quiero decir, el uso en si de Git/Github tiene unos beneficios directos de cara a nuestra productividad, pero GitHub ademas anyade beneficios de estar en una red donde hay mucha gente trabajando en cosas parecidas
Tambien, en algun lugar, ya que Alfonso @algarsal ha mencionado el tema de bitbucket y gitlab, ademas de que hay alternativas, mencionar  el tema de los repos privados, que GitHub ofrece la posibilidad de crear repositorios privados de manera gratuita para investigadores (academicos/estudiantes) y para grupos de investigacion:
https://help.github.com/articles/applying-for-an-academic-research-discount/

Para mi, en conjunto, representa muy bien lo que yo habria querido que me ensenyaran la primera vez que me abri la cuenta en GitHub. El empleo del poema como ejemplo me parece ademas muy acertada, mucho mas claro que el haber utilizado codigo.

Salud y buen fin de semana!
Fer

**Comment by ibartomeus** [comment]
Perfecto Javier. Yo creo que esta bien centrarse en GitHUb si esa es tu intención, pero dejar muy claro en la intro que es git y que es GitHub.

**Comment by Pakillo** [comment]
Muchas gracias por la nota @galeanojav !

Creo que es más fácil explicar todo esto en vivo que en un ms, pero creo que has conseguido dar un buen repaso al workflow y las funciones básicas. Subo aquí un Word con algunos comentarios/sugerencias

[ms_JGP_PACO.docx](https://github.com/ecoinfAEET/Notas_Ecosistemas/files/2152075/ms_JGP_PACO.docx)

Gracias!

**Comment by galeanojav** [comment]
Hola a todos, 

quería dar las gracias al grupo por los comentarios y la posibilidad de publicar la nota.  Ha sido muy divertido hacerlo y me ha encantado poder comentarlo con vosotros. 

Me he leído las otras notas y la verdad es que ojalá hubiese secciones parecidas en otras revistas, me parecen muy divertidas, interesantes y útiles. Además la posibilidad de hacer la revisión en el propio GitHub me ha parecido muy interesante. 

Subo aquí la versión corregida. Me he aprovechado bastante de los cambios propuestos por Paco, gracias mil,  espero haber recogido lo que comentabais.  

Lo dicho, estoy encantado y prometo repetir.

[ms_JGP_vfinal.docx](https://github.com/ecoinfAEET/Notas_Ecosistemas/files/2158775/ms_JGP_vfinal.docx)

Gracias mil

Javi

**Comment by ibartomeus** [comment]
Perfecto Javi. He hecho un par de comments más, y por mi o puedes subir a Ecosistemas. Envialo como Nota Ecoinformatica, y ya ira directo a maquetación. 
[ms_JGP_vfinal_IB.docx](https://github.com/ecoinfAEET/Notas_Ecosistemas/files/2160278/ms_JGP_vfinal_IB.docx)
