### ISSUE TITLE
Run Example rMarkdown template Error

### ISSUE THREAD

**Issue by ajcanepa** [ecoinfAEET/Notas_Ecosistemas#49]
Holas, muy buenas.
Lo primero, soy bastante nuevo en GitHub y si bien uso RMarkdown hace un tiempo, nunca lo he conectado con un gestor de referencias (o cualqueir archivo .bib) y estoy teniendo un error que no comprendo.

Simplemente me he descargado los 4 ficheros de [Notas_Ecosistemas/template](https://github.com/ecoinfAEET/Notas_Ecosistemas/tree/master/template), los he descargado en un directorio y cuando le doy a ejecutar todo el fichero `plantilla_NotaEcoinf.Rmd` me sale el siguiente error:

`Error in WriteBib(entry[order(keys)], file = file, append = append, ...) : 
  Must supply and object of class BibEntry `

Entiendo que está pasando algo con los ficheros `.bib` que he descargado, pero ni idea qué puede ser....

**Comment by Pakillo** [comment]
Gracias Antonio,

He simplificado la plantilla, prueba a descargártela de nuevo a ver.
Y asegúrate de tener bien instalado y actualizado knitcitations y sus dependencias (RefManageR, bibtex) porque el problema está por ahí...

Ya nos dices

**Comment by ajcanepa** [comment]
Buenas,
Lo he intentado nuevamente y me sigue dando el mismo error. Intento pegarles una captura de pantalla del error...

![image](https://user-images.githubusercontent.com/10628672/108223206-dc6ae680-7139-11eb-9899-73ff71ae6548.png)

**Comment by Pakillo** [comment]
Mmm eso es ejecutando el código de R directamente? Parece la consola. Para que funcione knitcitations tiene que ser dentro del entorno Rmarkdown, esto es dándole a Knit a todo el documento

**Comment by Pakillo** [comment]
De todas formas el uso de `knitcitations` es opcional... Yo lo uso para citar los paquetes de R automáticamente, pero hay otras opciones. Si quieres lo puedes quitar

**Comment by ajcanepa** [comment]
Efectivamente, eso salió cuando ejecuté todos los chunks a la vez, pero no "kniteándolo" si se me permitela expresión.
L aocsa está que cuando le doy KNIT a documento de Word, entrega los siguientes errores:

![image](https://user-images.githubusercontent.com/10628672/108224957-be9e8100-713b-11eb-9d84-344b6cebba5f.png)

**Comment by ajcanepa** [comment]
> De todas formas el uso de `knitcitations` es opcional... Yo lo uso para citar los paquetes de R automáticamente, pero hay otras opciones. Si quieres lo puedes quitar

Si al quitarlo te refieres a "borar" la línea 17 donde está la instrucción de `bibliography: - knitcitations.bib`, tampoco funciona, dando el siguiente error:

![image](https://user-images.githubusercontent.com/10628672/108225275-1210cf00-713c-11eb-8b50-43bda025d133.png)

Creo que debe ser algo de configuración del word o alguna incompatibilidad con Libreoffice / Ubuntu (que son los sistemas que uso)...igual tendría que haber comenzado por eso?

**Comment by Pakillo** [comment]
Yo también uso Ubuntu y Libre Office y no me da problemas...
Vuelve a la plantilla original que está en el repo. Si comentas la línea del YAML que pone csl: ecosistemas.csl, te va bien?

**Comment by ajcanepa** [comment]
Lo primero a aclarar es que cuando descargo a mi directorio local el fichero plantilla_NotaEcoinf.Rmd y la abro en Rstudio luce diferente a cómo se ve en el github

![image](https://user-images.githubusercontent.com/10628672/108228262-f9ee7f00-713e-11eb-9846-fe1e98085540.png)

Lo quehago es seleccionar todo en el github y pegarlo acá en el .Rmd local, pero me temo que esta visualización por defecto del fichero .Rmd tenga algo que ver con el problema...

**Comment by ajcanepa** [comment]
Ahora bien, cuando ejecuto el .Rmd comentando la línea del csl:
![image](https://user-images.githubusercontent.com/10628672/108229137-d11ab980-713f-11eb-9f7a-8b3365637efa.png)

el error que me entrega es:
![image](https://user-images.githubusercontent.com/10628672/108229239-ebed2e00-713f-11eb-82bd-7ff9b1ad67d0.png)

y hasta donde sé, tengo instalados todos esos paquetes...

**Comment by Pakillo** [comment]
ah no, no, ese Rmd no se ha descargado bien...

Descarga el repo entero en un zip (https://github.com/ecoinfAEET/Notas_Ecosistemas/archive/master.zip) o descargate el Rmd pero en raw (https://raw.githubusercontent.com/ecoinfAEET/Notas_Ecosistemas/master/template/plantilla_NotaEcoinf.Rmd)

Si lo prefieres puedes usar mi paquete rmdTemplates: https://github.com/Pakillo/rmdTemplates

**Comment by ajcanepa** [comment]
Pues por alguna razón lo que descargo del github no es igual, ya que al usar la que me envías en el zip, sí que me va bien, bueno casi.

Lo único es que me sale un warning:
![image](https://user-images.githubusercontent.com/10628672/108231435-0d4f1980-7142-11eb-8b43-551ab1087d1b.png)

y no se imprime el título, pero ya puedo renderizarlo en .docx...vamos avanazando!

![image](https://user-images.githubusercontent.com/10628672/108231724-5737ff80-7142-11eb-8e6b-110e0f82125c.png)

**Comment by ajcanepa** [comment]
Ya está!
Modifiqué un poco el YAML para qeu no tuviera `|` ni el quiebre de línea `\n`:

![image](https://user-images.githubusercontent.com/10628672/108232340-f6f58d80-7142-11eb-876d-4541e95da87c.png)

... y ya funciona el título!

![image](https://user-images.githubusercontent.com/10628672/108232256-dcbbaf80-7142-11eb-9d9f-058aa5a3ee2f.png)

Creo que con esto ya estaría resuelto, no?

**Comment by Pakillo** [comment]
Genial. Cierro entonces. El warning no hay que preocuparse.

**Comment by ajcanepa** [comment]
> Genial. Cierro entonces. El warning no hay que preocuparse.

Súper, Gracias por la ayuda!!
