### ISSUE TITLE
Revisión Cienciometria

### ISSUE THREAD

**Issue by ibartomeus** [ecoinfAEET/Notas_Ecosistemas#51]
Hola equipo, 

Os dejo una nueva nota sobre cienciometría para revisar durante la primera quincena de Junio (aprox.): https://github.com/ecoinfAEET/Notas_Ecosistemas/tree/master/cienciometria 

Podéis dejar vuestros comentarios para mejorar la nota en este hilo. Os recuerdo las normas de la revisión grupal: https://github.com/ecoinfAEET/Notas_Ecosistemas/blob/master/Normas_revision_grupal.MD

Muchas gracias de antemano!

Nacho y Paco

**Comment by ibartomeus** [comment]
Añado la revisión de Hugo Saiz: 

La nota me ha gustado mucho y me parece un tema muy necesario del que sabía poco. Recordar que todos los comentarios son sugerencias y los autores son libres de aceptarlos o no.

- No me ha quedado clara la diferencia entre bibliometría y cienciometría. En el primer párrafo se define expresamente bibliometría mientras que cienciometría se sugiere. Puesto que el título de la nota incluye cienciometría, creo que sería conveniente definirla.

L26, 'tema' me parece una palabra muy amplia. Creo que sería conveniente ser más específico (e.g. Cómo elegir nuestro tema de interés bibliométrico).
L30, el primer 'particular' se puede quitar.
L51 'Cómo'.
L67, si este dato sobre Venezuela es real estaría bien dar una referencia.
L71-80, sin querer defender expresamente a WOS etc, me parece que la escritura de esta sección es bastante subjetiva y da a entender que las grandes bases de datos de trabajos científicos son malas. Independientemente de que esto sea cierto o no (no soy experto en bases de datos bibliográficas), estas son las bases más utilizadas en investigación y creo que es más conveniente usar un lenguaje más neutro al abordar este tema y que el lector decida. Por ejemplo, en vez de recalcar 'solo es válido para el 3% de las publicaciones' (L80), lo cual ya sabemos porque la información se ha mencionado en la frase anterior, 'solo es válido para las publicaciones incluidas en estas bases de datos' condiciona menos al lector. Recordemos que la revista Ecosistemas la leen estudiantes y descubrir que las herramientas que conocen son insuficientes sin ofrecer ninguna alternativa puede no ser la mejor formación para el desarrollo de la capacidad científica crítica.    

Enhorabuena por la nota y gracias por contribuir a la revista.
Hugo

**Comment by garciacallejas** [comment]
Muchas gracias a los autores por esta nota tan interesante. Es un buen resumen de los pasos a seguir en estudios cienciométricos, algo que nos resulta muy lejano a muchos ecólogos.
Sólo tengo algunos comentarios:

Intro: de acuerdo con Hugo, sería interesante definir bibliometría y, después, hacerlo explicitamente con la cienciometría

- L12: vistas -> ¿visionados?
- L20: de la ecología -> sobre la ecología
- L26: De hecho, en este párrafo no se trata sobre "cómo" elegir el tema de interés, sino que se dan ejemplos comunes. Se puede cambiar el título del epígrafe por algo del estilo de "Etapa 1. Temas de interés bibliométrico", tal y como comenta Hugo.
- L45: Web Scraping, Murillo et al... -> Web Scraping: por ejemplo, Murillo et al...
- L51: Como -> Cómo
- L71-80: Totalmente de acuerdo con la sugerencia de Hugo. Por complementarla, sería pedagógico incluir una frase sobre este aparente vacío. ¿Por qué las grandes bases de datos deja fuera el 97% de revistas/publicaciones? ¿Cuestiones de idioma?
De todas formas, una nota eco-informática no es el lugar para profundizar en estos temas, por lo que con una mención muy somera bastaría. Igualmente, aunque sólo sea una cuestión semántica, yo personalmente dejaría fuera adjetivos como "extremadamente incompleta" o "igualmente insuficiente", y me limitaría a señalar los datos.
- L90-98 y Figura1: El ejemplo es muy interesante.  ¿Se puede incluir alguna referencia al software usado (VosViewer)? En el caso de que el ejemplo se pueda automatizar, que no sé si es posible, sería fantástico incluir el código/pseudocódigo en algún repositorio abierto. En paralelo, me surge la duda de hasta qué punto este ejemplo es unicamente bibliométrico y, en su caso, qué dimensiones alternativas se podrían considerar para que fuera un estudio cienciométrico. Esta pequeña duda creo que se solucinaría con una definición más explícita en la introducción.
- L94: Es un poco confuso decir en la linea 92 que el ejemplo es sobre abejas de las orquídeas, y en la línea 94 decir que predominan los artículos de ciencias médicas. Se puede especificar algo del estilo: "Como es de esperar, en la base de datos PubMed predominan los artículos enfocados a ciencias médicas (Fig. 1b). Por tanto, para un estudio cienciométrico sobre ecología, sería mejor..."

Gracias de nuevo, y enhorabuena por la nota
David

**Comment by lnfran85** [comment]
Muy muy interesante, nunca me había parado a pensar en este tema!

Aquí van algunos comentarios:

- L34: cambiaria ecologia y ecology por "ecologia" y "ecology" porque sobreentiendo que se trata de las palabras específicas utilizadas en la búsqueda

- L35-36: resumiría la frase un poco, como por ejemplo: Losdatos en masa (Big Data) tienen estructuras y formatos de diferentes fuentes, y por su gran....

- L65-66: re-estructuraría la idea en este sentido: Ladescriptiva, aunque es utilizada frecuentemente en las publicaciones, es lamenos robusta, y se limita a indicar frecuencias y porcentajes; 

- L72: eliminaría la coma despues del Es fácil que,

- L72: agregaria dos puntos después de   a hablar de:    

- L71: Este subtítulo me confunde un poco, porque habla de "cuidados a la hora de redactar", pero el párrafo a seguir no habla nada de redactar, está más enfocado en la interpretación de los resultados. Quizás podría enfocarse un poco mejor del estilo de "cuidados a la hora de interpretar los resultados"

- L71-80: Totalmente de acuerdo con Hugo y con David

- L96: Me he quedado un poco confundido con el concepto de big data. En esta línea se habla que es una técnica, mientras que en las 35-36 se habla que es un tipo de datos. Quizás se debería de aclarar este término

- L98: quizás resumiria en el tiempo por: patrones temporales

Muchas gracias y enhorabuena por la nota

Saludos,
Francisco

**Comment by algarsal** [comment]
Buenas,

Me parece un artículo muy interesante tal cual está.

Lo único que echo en falta es alguna cita a las publicaciones que ya 
existen sobre cómo se debe sistematizar la información en una "revisión 
sistemática", como el método PRISMA (Preferred Reporting Items for 
Systematic Reviews and Meta-Analyses).

Me refiero a la tabla 1 y figura 1 de este artículo:

https://www.acpjournals.org/doi/10.7326/0003-4819-151-4-200908180-00135

Considero que está bien que se sepa que cada vez está más estandarizado 
todo el proceso de recopilación de información y son muy útiles los 
esquemas y las listas de chequeo para ver que no te estás saltando 
ningún paso. Nosotros lo utilizamos como base metodológica para este 
artículo (ver figura 1 y primer párrafo de material y métodos):

https://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0223147

Saludos

Alfonso

**Comment by Pakillo** [comment]
Añado algunos comentarios/dudas:

L10: "más de 300.000 revistas científicas (Ulrich 2021)". No estoy seguro de si ese número es muy exacto. La database de Ulrich recoge "more than **300,00** periodicals of all types academic and scholarly journals, Open Access publications, peer-reviewed titles, popular magazines, newspapers, newsletters and more". "A limited selection of membership directories, comic books, and puzzle and game books is also included.".

Por tanto, parece que Ulrich incluye muchas cosas que no son revistas científicas. Por otro lado, ese "300,00" parece que le falta un 0 o la coma está desplazada... Al final, no me queda claro cuántas revistas científicas hay. ¿Hay otra fuente de información más fiable? Scopus y otras fuentes incluyen algo más de 30.000 revistas. ¿Es posible que nos estemos moviendo más en ese rango que en el de 300.000? Es un dato importante como para dar aquí una estima errónea que luego se propague. Si no se conoce bien, mejor no dar el dato, y mencionar simplemente que hay decenas de miles de revistas.


L10-16: Entiendo que la bibliometría trabaja con publicaciones (revistas, libros, etc) y la cienciometría incluye además altmetrics, webmetrics, etc, ¿es así?


L17: La expresión "producción ecológica" se asocia normalmente, al menos en España, a producción agroganadera. Sugiero cambiarlo por "cómo analizar la literatura científica en ecología", o algo así.


L34: Coincido con @lnfran85. Mejor entrecomillar "ecología" y "ecology"

L36-37: a mí me gusta la definición de Big Data que dan, que no se refiere solo a su volumen, sino también complejidad y velocidad de crecimiento (https://en.wikipedia.org/wiki/Big_data#Definition)


L63-70: Yo diría que hay más de dos formas de analizar. Primero, evitaría hablar peyorativamente de la estadística descriptiva, que no debe sobre-interpretarse pero es simplemente necesaria. Por otro lado, hay muchas formas de hacer inferencia estadística más allá del contraste de hipótesis. Propongo reescribir este párrafo.


L74-80: Nuevamente me surgen dudas sobre las coberturas de las distintas bases de datos. [Scopus](https://www.scopus.com/sources.uri) lista más de 30.000 revistas, casi 40.000. [Web of Science](https://clarivate.libguides.com/webofscienceplatform/coverage) también menciona entre 20.000 y 35.000 revistas. Y el número de 300.000 revistas científicas puede ser una sobre-estima, como mencioné antes. Por tanto, ese valor de 3% creo que es dudoso y sería preferible no mencionarlo (a menos que se encuentren estimas más fiables). Lo que sí está claro es que WoS y Scopus dejan fuera la inmensa mayoría de la literatura científica, con un sesgo muy notorio contra las ciencias sociales, publicaciones en otros idiomas, etc. Respecto a Google Scholar, no sabemos la cobertura que tiene pero sí que es la base de datos más exhaustiva con mucha diferencia. Creo que debería citarse [este artículo](https://doi.org/10.1016/j.joi.2018.09.002) de Martín-Martín et al. al respecto. 

Creo que aquí es importante también mencionar la importancia de considerar otros idiomas más allá del inglés (e.g. https://doi.org/10.1002/ece3.6368)


L93: Nuevamente creo que mejor no mencionar este dato del 97% a menos que pueda demostrarse su fiabilidad

Gracias

**Comment by Pakillo** [comment]
Nota publicada: https://doi.org/10.7818/ECOS.2256
