### ISSUE TITLE
¡Se puede entender cómo funcionan git & GitHub!

### ISSUE THREAD

**Issue by Pakillo** [ecoinfAEET/Notas_Ecosistemas#52]
Hola amigos,

¡Tenemos nueva nota ecoinformática para revisar! @Julenasti y @VeruGHub han escrito una nota explicando cómo funcionan git y GitHub. El manuscrito (en formato Word) está disponible [aquí](https://github.com/ecoinfAEET/Notas_Ecosistemas/blob/master/Git-GitHub_Astigarraga_CruzAlonso/2318-Texto%20del%20art%C3%ADculo-10878-1-2-20211118.docx).

Esperamos vuestros comentarios y sugerencias (ver [aquí](https://github.com/ecoinfAEET/Notas_Ecosistemas/blob/master/Normas_revision_grupal.MD) cómo funciona la revisión grupal). Os recuerdo que ya publicamos una nota sobre GitHub (https://doi.org/10.7818/ECOS.1604), por @galeanojav, por lo que estaría bien tener en cuenta los posibles solapamientos y formas de complementarse.

Sería ideal si pudiéramos tener la nota revisada antes del puente de Diciembre, por lo que esperamos recibir vuestros comentarios hasta el viernes **3 de Diciembre**.

Como siempre, gracias a tod@s por vuestra participación.

**Comment by CarlosLaraR** [comment]
Hola a tod@s,

Acabo de leer la nota. Me ha gustado. Es un tema complejo pero creo que habéis sabido contarlo de manera sencilla. Yo soy nivel usuario/principiante. Por ejemplo el tema de las ramas siempre me ha costado y con la explicación que dais me queda más claro.  Eso sí, creo que para una persona sin ninguna experiencia previa la sección sobre le flujo de trabajo es complicada. Pero es normal, e incluso en ese caso, la parte introductoria está genial para introducirse en el tema. Os dejo tres comentarios sin importancia.

Línea 50. Me pregunto si podéis utilizar otro término para "versiones descentralizadas" O añadir una coletilla explicativa. La frase completa, al tener también el concepto de "copia centralizada" se me hace un poco compleja. He tenido que pararme a leerla un par de veces.

Línea 52. ¿Mejor definir repositorio la primera vez que se utiliza el término?

L97. Supongo que será jerga pero la expresión "que contiene un puntero a un SHA específico " se ha hecho extraña por el término "puntero"

**Comment by CarlosLaraR** [comment]
Ah, y creo que las menciones a la nota anterior de Javi Galeano están muy bien. Es muy chulo ver cómo se van generando ramas interconectadas con las notas. Con los años podremos hacer un "git push" y juntar las notas con misma temática en un volumen específico. Perdonad la broma mala estoy falto de café ;)

**Comment by galeanojav** [comment]
Buenas, 

Perdonad que no me ha dado tiempo a mirármelo.
Me dejáis el puente para poder leérmelo?

Me parece una idea chulísima!!!

Javier

**Comment by saizhugo** [comment]
Hola,

me parece que la nota está bastante bien. Creo que las definiciones son claras y se entienden los básicos. Además, el material que se aporta al final es muy útil.

mi comentario principal sería que hay que suponer que la gente que lea la nota sabe 0 acerca del tema y algunas partes podrían hacerse más explícitas en eso. Pongo un par de ejemplos pero puede haber más.

Ejemplo 1: L66, creo que muchos lectores no saben que es Unix Shell, por lo que trataría de explicar le acceso de otra forma.
Ejemplo 2: es cierto que Google drive o dropbox no controlan versiones pero permiten modificar archivos .doc y guardar cambios (archivos con los que trabajan la mayoría de gente). En git, que yo sepa no se puede hacer cambios en .doc.

Espero que los comentarios sean útiles y gracias por hacer la nota.
Hugo

**Comment by algarsal** [comment]
Hola,

Acabo de leer la nota y me ha gustado mucho. Me parecen muy útiles las 
referencias web para ampliar información, bien elegidas. No tengo 
correcciones que hacer.

Saludos

Alfonso

**Comment by galeanojav** [comment]
Hola, 

ya me he podido leer la nota. 
Creo que está muy bien. 
Me ha gustado mucho cómo se cuentan los cuatro espacios de trabajo y las figuras que habéis utilizado para contarlas. 

Enhorabuena por el artículo 

Javier

**Comment by josesalgr** [comment]
Hola,

Acabo de leer la nota y me parece que el tema está bien abordado y de forma concisa. 
Concuerdo con uno de los comentarios anteriores sobre el uso como ejemplo de Unix shell (L66), quizas el público objetivo no esté familiarizado con este término. Asimismo, se utilizan términos en inglés como "pull" o "push", y otros como "ramas" en castellano. Quizás sea oportuno llamarles (o nombrar la primera vez que aparece) su expresión en inglés.

Espero que el comentario sea un aporte!
Gracias por la nota

José

**Comment by josesalgr** [comment]
Hola,

Acabo de leer la nota y me parece que el tema está bien abordado y de forma concisa. 
Concuerdo con uno de los comentarios anteriores sobre el uso como ejemplo de Unix shell (L66), quizas el público objetivo no esté familiarizado con este término. Asimismo, se utilizan términos en inglés como "pull" o "push", y otros como "ramas" en castellano. Quizás sea oportuno llamarles (o nombrar la primera vez que aparece) su expresión en inglés.

Espero que el comentario sea un aporte!
Gracias por la nota

José

**Comment by Pakillo** [comment]
Muchas gracias a todos por los comentarios.

@Julenasti @VeruGHub aporto algunos más en el archivo adjunto, con control de cambios. 

[2318-Texto del artículo-10878-1-2-20211118.docx](https://github.com/ecoinfAEET/Notas_Ecosistemas/files/7692141/2318-Texto.del.articulo-10878-1-2-20211118.docx)

**Comment by Pakillo** [comment]
> Ejemplo 2: es cierto que Google drive o dropbox no controlan versiones pero permiten modificar archivos .doc y guardar cambios (archivos con los que trabajan la mayoría de gente). En git, que yo sepa no se puede hacer cambios en .doc.

Google Docs ha mejorado muchísimo últimamente en cuanto a control de versiones. Ya te permite guardar versiones concretas y nombrarlas, como si estuvieras haciendo commit, y por supuesto volver a versiones anteriores. 

Con git puedes trackear archivos Word, PDF, Excel, para mantener un historial de versiones. Pero es cierto que git no está pensado para eso

**Comment by Pakillo** [comment]
@Julenasti @VeruGHub si podéis enviar la versión revisada pronto, a lo mejor puede entrar en el próximo número de Ecosistemas, que debe salir a finales de Diciembre. Gracias

**Comment by Julenasti** [comment]
Hola a todos,

Muchas gracias por vuestros comentarios. Han mejorado significativamente la nota.

Os respondemos brevemente a vuestros comentarios:

> Línea 50. Me pregunto si podéis utilizar otro término para "versiones descentralizadas" O añadir una coletilla explicativa. La frase completa, al tener también el concepto de "copia centralizada" se me hace un poco compleja. He tenido que pararme a leerla un par de veces.
Hecho incluyendo figura explicativa: “GitHub contiene la copia centralizada del control de versiones distribuido o descentralizado (Fig. 2).”
> Línea 52. ¿Mejor definir repositorio la primera vez que se utiliza el término?
Hecho (línea 47)
> L97. Supongo que será jerga pero la expresión "que contiene un puntero a un SHA específico " se ha hecho extraña por el término "puntero"
Hecho. Puntero (pointer) es el término que se utiliza (https://www.atlassian.com/es/git/tutorials/using-branches) pero hemos añadido las palabras enlace y pointer en el texto: “En Git, una rama es un commit al que le se le da un nombre y que contiene un “enlace” (puntero o _pointer_) a un SHA específico que es el origen de la rama”. 

> Ejemplo 1: L66, creo que muchos lectores no saben que es Unix Shell, por lo que trataría de explicar le acceso de otra forma. 
Hecho. Hemos añadido una referencia y la palabra terminal: Si se ejecuta Git desde la línea de comandos de _Unix shell_ (para más información sobre el _shell_ o terminal ver https://happygitwithr.com/shell.html#shell), la transición entre zonas de trabajo se realiza mediante comandos (Fig. 4). 
> Ejemplo 2: es cierto que Google drive o dropbox no controlan versiones pero permiten modificar archivos .doc y guardar cambios (archivos con los que trabajan la mayoría de gente). En git, que yo sepa no se puede hacer cambios en .doc.
Hecho. Sí, Dropbox no es el mejor ejemplo. Hemos añadido otros ejemplos de control de versiones centralizados: “(p. ej. Subversion (SVN, <https://subversion.apache.org/>) o Concurrent Versions System (CVS, <http://cvs.nongnu.org/>))”.

> Hola, Acabo de leer la nota y me ha gustado mucho. Me parecen muy útiles las referencias web para ampliar información, bien elegidas. No tengo correcciones que hacer. 
Muchas gracias!

> ya me he podido leer la nota. Creo que está muy bien. Me ha gustado mucho cómo se cuentan los cuatro espacios de trabajo y las figuras que habéis utilizado para contarlas.
Muchas gracias!

> Acabo de leer la nota y me parece que el tema está bien abordado y de forma concisa. Concuerdo con uno de los comentarios anteriores sobre el uso como ejemplo de Unix shell (L66), quizas el público objetivo no esté familiarizado con este término. Asimismo, se utilizan términos en inglés como "pull" o "push", y otros como "ramas" en castellano. Quizás sea oportuno llamarles (o nombrar la primera vez que aparece) su expresión en inglés.
Hecho. Hemos añadido (branch) la primera vez que aparece el término rama.

> @Julenasti @VeruGHub aporto algunos más en el archivo adjunto, con control de cambios.
Adjuntamos el word con tus respuestas

La nota revisada está aquí: 

De nuevo, muchas gracias  a todos!

Vero y Julen

**Comment by Pakillo** [comment]
Hola @Julenasti @VeruGHub 

Muchísimas gracias por vuestra revisión, y por considerar seriamente todos los comentarios recibidos. Me encantan las nuevas figuras, y creo que la nota ha quedado muy clara y será muy útil para muchos. 

El siguiente paso sería subir la nota revisada en la plataforma de la revista, para su aceptación formal y maquetación.

Gracias de nuevo y enhorabuena
