### ISSUE TITLE
Camelot: Una herramienta intuitiva para el manejo y procesamiento de imágenes de cámaras trampa utilizando inteligencia artificial

### ISSUE THREAD

**Issue by Julenasti** [ecoinfAEET/Notas_Ecosistemas#55]
Hola a tod@s,

¡Tenemos nueva nota ecoinformática para revisar! @Jennerodas ha escrito una nota explicando cómo funciona el software informático Camelot para el manejo y procesamiento de imágenes de cámaras trampa utilizando inteligencia artificial. 

Archivo Word:
[camelot_rodas-trejo.docx](https://github.com/ecoinfAEET/Notas_Ecosistemas/files/14979952/camelot_rodas-trejo.docx)

Queda abierta la revisión grupal hasta el día 6 de mayo. [Aquí](https://github.com/ecoinfAEET/Notas_Ecosistemas/blob/master/Normas_revision_grupal.MD) podéis leer cómo funciona el proceso de revisión abierta.

Como siempre, gracias a tod@s por vuestra participación.

**Comment by garciacallejas** [comment]
Hola! muchas gracias Jenner por la nota. Leyendo el documento, me ha dejado una sensación un poco ambivalente. El software seguro que es interesante para investigadores/as que no lo conozcan, y la introducción sobre las cámaras trampa es muy apropiada, ¡buen trabajo!. Sin embargo, tal y como está estructurado parece en buena medida un manual resumido sobre las cuestiones técnicas de su instalación y uso, nada que no pueda consultarse en los documentos de ayuda del propio software. 

Por ejemplo, en las limitaciones para grandes conjuntos de datos (lineas 40 y siguientes) se ha copiado información directamente del manual de usuario en 

https://camelot-project.readthedocs.io/en/latest/scale.html#limitations

En mi opinión, estas secciones relativas a la instalación y requerimientos de hardware (lineas 27-50) podrían eliminarse practicamente por completo, ya que cualquier usuario puede fácilmente leer el manual online, y eso permitiría centrar la nota en las aplicaciones del programa. Por ejemplo, creo que sería muy enriquecedor enfocar la nota alrededor de un caso práctico con una o varias preguntas de investigación que reflejen las capacidades del software. Tal y como comenta el autor, la generación de informes y la importación de datos puede ser compleja para usuarios nuevos: ¿porqué no adaptar la nota para presentar un caso completo que aborde cuestiones como esas?

En ese sentido, y de nuevo en mi opinión, las figuras 1,3, y posiblemente 4 no aportan demasiado, y las líneas 56-76 también parece información fácilmente consultable en el manual oficial. La figura 2 es más explicativa, y puede servir de anclaje para la estructura de la nota.

Espero que estos comentarios sean útiles, ¡gracias de nuevo, Jenner!
Salud
David

**Comment by Jennerodas** [comment]
Hola David, agradezco mucho tus comentarios y observaciones, son muy bien
recibidas, me parece muy oportuno lo que comentas y podría hacer la nota a
un caso en específico, enfocar hacia el funcionamiento de etiquetado y
búsquedas, así como el uso de los reportes que son una herramienta muy
potente que presenta el programa.

¿Trabajo las adecuaciones o esperamos más comentarios?


un abrazo

**Comment by Julenasti** [comment]
Muchas gracias por los comentarios David. Jenner, como la revisión está abierta hasta el día 6 de mayo aún espera antes de incluir las sugerencias para ver qué opinan los demás revisores. Una vez tengamos los comentarios de todos los revisores ya te indicaremos nosotros como proceder para incluir las sugerencias.

**Comment by Jennerodas** [comment]
Vale, muchas gracias.

**Comment by Julenasti** [comment]
Hola Jenner,

Después de una lectura detallada de la nota, estoy totalmente de acuerdo con lo que indicaba David hace unos días. Como indica David, creo que una buena opción sería enfocarlo a un caso práctico donde puedas responder alguna pregunta concreta y a lo largo de la nota vayas explicando/mostrando su funcionamiento, indicando las fortalezas y debilidades, etc. Por ello, mi sugerencia sería intentar cumplir dos objetivos: 1-que si alguien en el día de mañana vaya a trabajar con imágenes de cámaras trampa sepa como trabajar con Camelot más allá de lo que se explica en el manual de usuario (funcionamiento, fortalezas, debilidades, etc.); 2-en ese proceso explicativo abordar una pregunta ecoinformática.

Te recomendamos que valores las sugerencias de David y mías, y que si quieres seguir en el proceso de revisión, cuando tengas la siguiente versión lo pusieras en este issue. Asímismo, te agradeceríamos que en el mismo issue nos indicaras los cambios que has hecho respecto a la anterior versión. Cualquier duda nos dices. 

Muchas gracias,
Julen

**Comment by Jennerodas** [comment]
Hola julen gracias por sus comentarios, iniciare el proceso de re escritura basado en sus observaciones y comentarios, ¿ hay tiempo limite?, espero tenerlo en una o dos semanas máximo, ya que me encuentro a finales de cursos y toca leer muchos trabajos. Si no hay problema con el tiempo en cuanto lo termine io subo. Espero sus comentarios, un abrazo,

Jenner

**Comment by Julenasti** [comment]
Hola Jenner, me alegro que vayas a considerar las sugerencias. Está bien las fechas que indicas incluso si necesitas más tiempo. A priori no solemos poner tiempo límite pero si preves que te va a llevar bastante tiempo (p. ej. más de 1-2 meses) te agradeceríamos que nos lo indicaras. Principalmente para saber cúal es tú intención con la nota. 
Quedamos a la espera de la nota,
Julen

**Comment by Jennerodas** [comment]
Hola Julen , la nota la la tendría en 2 semanas máximo, espero mucho antes, la idea es continuar con el proceso lo más pronto posible y estar en condiciones de enviarla a revisión en unos días.

en cuanto la tenga lista la agrego 

saludos 

Jenner

**Comment by Julenasti** [comment]
Estupendo Jenner, muchas gracias!

**Comment by Jennerodas** [comment]
Estimados Julen y David, les hago llegar la modificación del manuscrito, espero haber cumplido cabalmente con las observaciones. Quedo en espera de sus comentarios. 

Un abrazo 

Jenner
[camelot_rodas-trejorev.docx](https://github.com/ecoinfAEET/Notas_Ecosistemas/files/15284281/camelot_rodas-trejorev.docx)

**Comment by Julenasti** [comment]
Hola Jenner,

Muchas gracias por la rapidez. Esperamos tener otra ronda de revisión terminada como tarde para finales de mayo. A ver si David puede. También hemos contactado con dos personas con experiencia en trabajar con imágenes en cámaras trampa. Cuando tengamos todas las revisiones te avisamos.

Un saludo,

Julen

**Comment by Julenasti** [comment]
Nota para los revisores: hemos actualizado las [directrices para los revisores de las notas](https://github.com/ecoinfAEET/Notas_Ecosistemas/blob/master/directrices_revisores.MD) en la [página web](https://ecoinfaeet.github.io/website/notas-ecoinformaticas.html) para ayudaros en el proceso de revisión. ¡Esperamos que os resulten útiles!

**Comment by PabloQuilesTundidor** [comment]
Hola Jenner
Lo primero de todo, siento mucho la tardanza. Lo segundo, gracias por la nota. Desde alguien que se ha pegado directamente con el código de python de MegaDetector, y con un flujo de trabajo posterior menos eficiente (y auto-infligido), creo que dar a conocer este tipo de herramientas y las diferentes opciones que hay, ayuda a que el uso de cámaras trampa sea más extensivo y viable a la vez.
En cuanto al documento, estoy de acuerdo con lo que comenta David, creo que seguir un caso práctico ayuda mucho a un posible investigador que quiera usar este software. En este sentido tengo algunas dudas relativas al tiempo de procesado que quizás sean interesantes para el lector: (i) ¿Cómo de rápida es la subida de imágenes? (ii) ¿Es un proceso eficaz si tienes multitud de EMs?
Mi duda principal es cómo es la integración de la IA (comentas MegaDetector), pero leyendo el documento y la bibliografía ofreces, Camelot tiene la ventaja de aceptar el ouput que da MegaDetector, pero no veo en que manera usa IA más allá de eso. Si tiene alguna aplicación relativa al uso de IA habría que explicarlo un poco más.
Esto es muy importante, ya que el hecho de que la IA (MegaDetector) filtre aquellas imágenes "vacías" es lo que realmente reduce el tiempo de procesado y hace viable proyectos de fototrampeo a gran escala.
En cuanto a ventajas y en base a esta duda anterior, compararía este software con otros similares para destacar qué aporta diferente, comparándolo con otros gestores de imágenes como XnView, EcoAssist, etc
En cuanto a desventajas quizás añadiría que la extracción de datos va dirigida a CamtrapR y Overlap; que no son malas opciones, pero igual si se busca un análisis diferente, el flujo de trabajo no es tan sencillo.
Otros comentarios puntuales:
L12: preguntas ecológicos -> preguntas ecológicas
L82-83: Muy importante que no anide datos sitio de muestro y CT, ya que da flexibilidad a la hora de elegir variables relativas a la ocupación/abundancia de las especies y su detectabilidad
L93-96: Aquí o en general en el texto, ¿Cómo de fácil/difícil es extraer los datos en un formato que permita usar otros análisis en R como unmarked o spOccupancy? Por curiosidad propia y por si al lector le fuera de utilidad.
Espero que mis comentarios sean útiles, y gracias de nuevo.
Un saludo
Pablo

**Comment by loretobaroja** [comment]
Hola, Jenner:

¡Muchas gracias por animarte a escribir la Nota Ecoinformática sobre Camelot y presentarnos este software! Seguro que es muy útil para todas aquellas personas que trabajamos con cámaras de fototrampeo pero no lo conocíamos.

Estoy de acuerdo con Pablo en que sería interesante tener una comparación de esta herramienta con otras como Megadetector, Agouti, etc. No sé si tienes esta información, si no la tienes no pasa nada, pero si la tienes sería muy buena idea compartirla.
Creo que sería interesante saber el porcentaje medio de acierto/error que tiene el software. Probablemente dependerá de muchas variables como el tamaño de la especie, la distancia, la nitidez de la imagen, etc., pero estaría bien una media, si dispones del dato.
Otra información que podrías compartir (si te parece interesante, si ya lo tienes y no interfiere con resultados que quieras publicar) es una parte del código relacionada con el ejemplo que has usado en el texto usando los paquetes que mencionas en la línea 95.
Comentarios menores y algunos errores tipográficos:
L 12. “preguntas ecológicas” en lugar de “preguntas ecológicos”.
L 19. Borrar la coma después de “trabajo”.
L 23. “Qué” en lugar de “Que”. 
L 32. “está” en lugar de “esta”.
L 46. Quizá puedes considerar cambiar “locación” por “localización”, que suele ser más común.
L 59. Añadir “,” después de “Además”.
L 64. “perdida” en lugar de “pérdida”.
L 67. “dará” en lugar de “dara”.
L 69. “imagen” en lugar de “imágen”
L 94. “descargó” o “descarga”, lo que prefieras, en lugar de “descargo”.
L 95. El paquete “camtrapR” creo que es con c minúscula. “preparara” (sobra un ra al final). El paquete “overlap” creo que es con o minúscula.
L 99. Eliminar la “,” después de “que”.
L 104. Eliminar la “,” después de “Camelot”.
L 109-110. Quizás podrías considerar escribir esta referencia tipo oración, como el resto: “Animal identification in low quality camera-trap images using very deep convolutional neural networks and confidence thresholds”
Figura 2. En el cuadro: “Información de la estructura raíz”, añadir el acento en la i.
Por supuesto, son sugerencias, siéntete libre de aceptar o rechazar lo que te parezca oportuno.
Saludos
Loreto

**Comment by loretobaroja** [comment]
Hola, Jenner:

¡Muchas gracias por animarte a escribir la Nota Ecoinformática sobre Camelot y presentarnos este software! Seguro que es muy útil para todas aquellas personas que trabajamos con cámaras de fototrampeo pero no lo conocíamos.

Estoy de acuerdo con Pablo en que sería interesante tener una comparación de esta herramienta con otras como Megadetector, Agouti, etc. No sé si tienes esta información, si no la tienes no pasa nada, pero si la tienes sería muy buena idea compartirla.

Creo que sería interesante saber el porcentaje medio de acierto/error que tiene el software. Probablemente dependerá de muchas variables como el tamaño de la especie, la distancia, la nitidez de la imagen, etc., pero estaría bien una media, si dispones del dato.

Otra información que podrías compartir (si te parece interesante, si ya lo tienes y no interfiere con resultados que quieras publicar) es una parte del código relacionada con el ejemplo que has usado en el texto usando los paquetes que mencionas en la línea 95.

Comentarios menores y algunos errores tipográficos:
- L 12. “preguntas ecológicas” en lugar de “preguntas ecológicos”.
- L 19. Borrar la coma después de “trabajo”.
- L 23. “Qué” en lugar de “Que”. 
- L 32. “está” en lugar de “esta”.
- L 46. Quizá puedes considerar cambiar “locación” por “localización”, que suele ser más común.
- L 59. Añadir “,” después de “Además”.
- L 64. “perdida” en lugar de “pérdida”.
- L 67. “dará” en lugar de “dara”.
- L 69. “imagen” en lugar de “imágen”
- L 94. “descargó” o “descarga”, lo que prefieras, en lugar de “descargo”.
- L 95. El paquete “camtrapR” creo que es con c minúscula. “preparara” (sobra un ra al final). El paquete “overlap” creo que es con o minúscula.
- L 99. Eliminar la “,” después de “que”.
- L 104. Eliminar la “,” después de “Camelot”.
- L 109-110. Quizás podrías considerar escribir esta referencia tipo oración, como el resto: “Animal identification in low quality camera-trap images using very deep convolutional neural networks and confidence thresholds”
- Figura 2. En el cuadro: “Información de la estructura raíz”, añadir el acento en la i.

Por supuesto, son sugerencias, siéntete libre de aceptar o rechazar lo que te parezca oportuno.

¡Saludos!
Loreto

**Comment by Julenasti** [comment]
Hola a todos, 

Muchas gracias @Jennerodas por considerar nuestras sugerencias anteriores. También, agradecer a Pablo y Loreto por revisar la nota, que son dos personas con una amplia experiencia en el mundo del fototrampeo. 

Personalmente, creo que esta versión de la nota está mucho más orientada hacia la publicación final. Por ello, esta vez en lugar de una reestructuración de la nota, te pediría que valoraras las sugerencias de Pablo y de Loreto. Te agradecería que en la siguiente versión nos indicaras dónde has incluido sus sugerencias y en caso de que no las hayas incluido nos indicaras el motivo. A su vez, puesto que Loreto habla de compartir código creo que está bien tener en cuenta [esto](https://github.com/ecoinfAEET/Notas_Ecosistemas/blob/master/directrices_revisores.MD), y también recordar que requerimos citar los paquetes de R que se mencionan en las notas.

Quedamos a la espera de la siguiente versión.

Muchas gracias,

Julen

**Comment by Jennerodas** [comment]
Hola Loreto, Pablo y Julen,  muchas gracias por sus comentarios a la nota, trabajare en ellos en los próximos días y en cuanto los tenga se los hago llegar nuevamente. 

Saludos 

Jenner

**Comment by Jennerodas** [comment]
Hola Loreto, Pablo y Julen les comparto el archivo con las observaciones integradas en rojo para que se identifiquen asi mismo por este lado les comento puntualmente como fueron atendidas:

Comentario 1.- (i) ¿Cómo de rápida es la subida de imágenes? (ii) ¿Es un proceso eficaz si tienes multitud de EMs?

Atendido: Camelot no presenta límite de cantidad de datos que puede admitir, su rendimiento para la carga de imágenes y otras funciones depende de la memoria física de la computadora, por ejemplo para el manejo de 100000 imágenes se requiere un mínimo de memoria física de 4096 MB. L 66-69

Por el numero de palabras no ingrese la valoracion que hacen los autores de Camelot sobre el programa que indican que con 2 millones de imágenes funcionó bien en el 99% de los conjuntos de datos. Y la mención que para trabajar con esa cantidad de imágenes usando una computadora portátil de alta gama Dell Precision 5510, obtuvieron rendimientos muy buenos en tiempo de carga de imagenes, búsqueda y exportación (menos de 1 minuto), pero que depende de la memoria física de la lap.

Comentario 2.- Si tiene alguna aplicación relativa al uso de IA habría que explicarlo un poco más.

Se aclara que Camelot utiliza la IA con la salida del modelo MegaDetector para agilizar el flujo de trabajo semi-automatizado en el filtrado de imágenes que contiene fauna o personas L 24-26.


Comentario 3.- En cuanto a ventajas y en base a esta duda anterior, compararía este software con otros similares para destacar qué aporta diferente, comparándolo con otros gestores de imágenes como XnView, EcoAssist, etc

Respuesta: Encontré algunos trabajos donde comparan algunas plataformas que utilizan IA en la gestión de imágenes de CT teniendo ventajas y desventajas en identificación, filtrado, reconocimiento diferente, etc. Para Camelot únicamente encontre una comparación de funciones de rendimiento con Timelapse, en la que indican que dentro de las ventajas que presenta Camelot se encuentra: el uso del programa en varios sistemas operativos, la importación manual o por CSV masiva de información de CT (colocación, etc), la organización de los datos para la generación de reportes, el acceso y trabajo remoto y la reducción de los datos utilizando un umbral de independencia temporal específico y reglas predeterminadas adicionales en Camelot.  No indican rendimiento y exactitud de clasificación de imágenes ni cual es mejor programa. 
 
Por la búsqueda que realice al parecer hace faltan comparaciones de rendimiento entre programas.
En desventaja se indica que no puede trabajar videos y su rendimiento se ve afectado cuando se trabaja con conjuntos de datos muy grandes.

Por eso no se agrega la comparación de Camelot con otros programas, aunque sería muy interesante ya que si existen trabajos de otros programas o técnicas de IA usadas en la gestión de imágenes. 

Comentario 4.- En cuanto a desventajas quizás añadiría que la extracción de datos va dirigida a CamtrapR y Overlap; que no son malas opciones, pero igual si se busca un análisis diferente, el flujo de trabajo no es tan sencillo.  
L93-96: Aquí o en general en el texto, ¿Cómo de fácil/difícil es extraer los datos en un formato que permita usar otros análisis en R como unmarked o spOccupancy? Por curiosidad propia y por si al lector le fuera de utilidad

Se atendió: Entre las desventajas que presenta Camelot a diferencia de otras plataformas, es que no realiza directamente el reconocimiento de especies, ni encuadra la imagen del animal, además que la generación de informes personalizados para otros programas o paquetes de R como unmarked (Kellner et al. 2023) o spOccupancy (Doser et al. 2022), así como la importación masiva de datos es complicada para usuarios nuevos. Algunas tareas, como la carga y búsqueda de imágenes, pueden volverse lentas a medida que aumenta el tamaño del conjunto de datos. (L 113-118)


Comentario 5.- L82-83: Muy importante que no anide datos sitio de muestro y CT, ya que da flexibilidad a la hora de elegir variables relativas a la ocupación/abundancia de las especies y su detectabilidad

Se atendió: A diferencia de otros pogramas, Camelot no anida la información de los sitios de muestreo y CT dentro del proyecto, lo que da flexibilidad a la hora de elegir variables relativas a la ocupación/abundancia de las especies y su detectabilidad. L 84-86

Comentario 6.- Creo que sería interesante saber el porcentaje medio de acierto/error que tiene el software. 

Lo que comentaba anteriormente que no se ha realizado una evaluación directa a Camelot pero si a megadetector y en diferentes trabajos se reportan arriba de 95% de aciertos en diferentes condiciones, pero esto no fue integrado, ¿consideran importante agregar este dato?

Comentario 7.- Otra información que podrías compartir (si te parece interesante) es una parte del código relacionada con el ejemplo que has usado en el texto usando los paquetes que mencionas en la línea 95.

Se atendio modificando el siguiente párrafo: Para comparar los PAD entre dos especies de interés, se descarga el reporte “CamtrapR Record Table” y se realiza el análisis con el paquete overlap de R (Meredith y Ridout 2021) (Fig 5). Como ejemplo seleccionamos las especies Nasua narica y Pecari tajacu que presentan más de 50 registros por lo cual utilizamos el estimador “Dhat4” (Meredith y Ridout 2021). L 98-110

Además agregue el código y el gráfico resultante (¿consideran este último útil?). 

Por último: Se atendieron los errores de ortografía y sintaxís que señalaron. 


Agradezco mucho sus observaciones fueron muy enriquecedoras, por favor si alguna no fue atendida debidamente o pasado por alto indiquenme para atender inmediatamente, así mismo si existen otras observaciones que ustedes consideren que ayuden al trabajo a ser más presentable. 

Quedo al pendiente 

Un abrazo 
[camelot_rodas-trejorev01.06.24.docx](https://github.com/user-attachments/files/15522836/camelot_rodas-trejorev01.06.24.docx)


Jenner

**Comment by Julenasti** [comment]
Muchas gracias por considerar las sugerencias Jenner. @PabloQuilesTundidor y @loretobaroja podríais valorar las respuestas de Jenner a vuestras sugerencias por favor? Os va bien mirarlo antes del día 21 de junio? Si necesitais más tiempo decídmelo por favor

**Comment by PabloQuilesTundidor** [comment]
Hola Jenner
Gracias por tener en cuenta nuestros comentarios. Por mi parte, salvo un par de modificaciones que ahora te comento, estoy más que conforme con las modificaciones. Sobre este tema se puede escribir largo y tendido, pero como introducción o de cara a que los investigadores sean conscientes de la existencia y las posibilidades que da este software, es más que suficiente.

L24-26: Lo cambiaría por:
"Camelot es un software gratuito con una interfaz intuitiva que facilita la gestión de imágenes de CT, **ofreciendo un siguiente paso natural al filtrado automático de imágenes que ofrece la IA del modelo MegaDetector y así** agilizar el flujo de trabajo semi-automatizado en el filtrado de imágenes que contiene fauna o personas (Vélez et al. 2022)."
L114-118: Lo cambiaría por:
"**ni genera** informes personalizados para otros programas o paquetes como unmarked (Kellner et al. 2023) o spOccupancy (Doser et al. 2022).  **Además,** la importación masiva de datos puede ser complicada para usuarios nuevos **y** algunas tareas, como la carga y búsqueda de imágenes, pueden volverse lentas a medida que aumenta el tamaño del conjunto de datos."

Lo dicho, por mi parte el trabajo está genial, ¡muchas gracias por el esfuerzo!
Un saludo
Pablo

**Comment by Jennerodas** [comment]
Muchas gracias por tus comentarios Pablo, hare los cambios que me indicas, espero entonces Julen 


Muchas gracias 

Saludos

**Comment by loretobaroja** [comment]
Hola, @Jennerodas:

¡Gracias por considerar las sugerencias sobre tu nota y atender la mayoría de ellas!

Gracias también por compartir una parte del código con el ejemplo de la actividad diaria de dos especies mostrando la aplicación que puede tener. Sobre la gráfica, a mí sí me parece interesante para ver el tipo de figuras que se pueden llegar a conseguir con la información filtrada con Camelot, pero esta es mi opinión, siéntete libre de incluirla o no.

Sí que creo que es interesante añadir la información sobre el porcentaje de aciertos, quizá también puedes aportar algo desde tu propia experiencia, es decir, cómo de precisa ha sido esta herramienta con tus datos. Muchas de las personas que leemos sobre este tema lo que queremos saber es si merece la pena invertir tiempo en aprender a usar este tipo de herramientas. Si identifica correctamente en el 95% de los casos y en función de la cantidad de imágenes que se quieran analizar la respuesta probablemente será que sí 😊. Creo que con una frase corta sería más que suficiente en caso de que tú también lo consideres interesante.

Algunos errores tipográficos:
• L 11: eliminar la coma después de (CT).
• L 68: añadir “,” después de “por ejemplo”.
• Creo que en el paquete “**c**amtrapR”  la c es minúscula.
• L 102: falta la r de ove**r**lap.

¡Gracias de nuevo por animarte a escribir la nota! Es una buena presentación de esta herramienta. 

Saludos
Loreto

**Comment by Jennerodas** [comment]
Hola Loreto y Pablo, muchas gracias por los comentarios y observaciones,  fueron muy enriquecedores y ya fueron integrados al documento. Julen, envio la versión con los comentarios integrados, en rojo coloque la ultima recomendación de Loreto. 

Anexo el documento. 

[camelot_rodas-trejorev11.06.24.docx](https://github.com/user-attachments/files/15792064/camelot_rodas-trejorev11.06.24.docx)

Quedo al pendiente de tus comentarios. 


Un abrazo!!!

Jenner

**Comment by Julenasti** [comment]
Evitaría las abreviaciones en la medida de lo posible. Por ejemplo, ANP se utiliza solo dos veces en el texto por lo que creo que no merece la pena abreviarlo. Lo mismo ocurre con PAD. CT, aunque se utilice más a lo largo del texto tampoco lo abreviaría. Creo que utilizar el término completo añade claridad. Por favor, revisa las abreviaciones que utilizas y reemplázalos por los términos completos en la medida de lo posible.

L12: ..., ayudando a los científicos a responder preguntas ecológicas
L13: Las CT generan una gran cantidad...
L18: Una herramienta interesante que ha integrado IA y CT es el software Camelot
L26: MegaDetector, y así agilizar



sigo, esperad por favor

**Comment by Jennerodas** [comment]
Estimado Julen envio la nota con las observaciones realizadas. Así mismo te envio el archivo para testear el código. En la sección de Disponibilidad de datos, coloque un enalce de GitHub donde coloque el archivo CSV con los datos completos del muestreo, solamente las coordenadas fueron levemente modificadas porque trabajo en un artículo con esa base de datos. Avisame por favor si esta bien asi. También cargue el archivo CSV y código para correr el análisis de Patrones de actividad. Agregue agradecimientos a la nota

Quedo al pendiente de cualquier comentario.

Un abrazo 

Jenner

[camelot_rodas-trejorev18.06.24.docx](https://github.com/user-attachments/files/15893990/camelot_rodas-trejorev18.06.24.docx)

[record-table_2024-05-31_2008.csv](https://github.com/user-attachments/files/15893991/record-table_2024-05-31_2008.csv)

**Comment by Julenasti** [comment]
He visto que has sustituido CT por cámaras trampa. Muchas gracias por seguir la sugerencia pero al hacerlo a veces mezclas el plural con el singular. Revísalo por favor (L49, 59, 61, 66, etc.)

Se te ha pasado corregir estas dos pequeñas erratas. Las erratas están en las figuras mismas y aquí mis sugerencias de cómo deberían figurar:
- En la Figura 2: Gestor para la integración de la base de datos de especies; Configuración del proyecto
- En la Figura 3. Panel para la visualización de la imagen; Gestor de información de la imagen para la clasificación

- L139. Es el grupo de Ecoinformática de la AEET ;)


sigo
