### ISSUE TITLE
Acceso a datos programaticamente

### ISSUE THREAD

**Issue by ibartomeus** [ecoinfAEET/Notas_Ecosistemas#7]
Inicio n borrador de nota sobre acceso a datos dando a conocer @ropensci : https://github.com/ecoinfAEET/Notas_Ecosistemas/blob/master/notas/ropensci.Rmd 

Contribuciones bienvenidas, y naturalmente resultan en co-autoria de la nota.

**Comment by Pakillo** [comment]
Genial Nacho. Te parece bien si la formateo para que genere un Word listo para Ecosistemas? (https://github.com/Pakillo/rmdTemplates/issues/11).
Mucha suerte fichando colaboradores! :)

**Comment by ajpelu** [comment]
Ey!! genial Idea Nacho!! 

Yo hace tiempo (2014) contribuí con ropensci en un case study utilizando rgbif. Puedes verlo aqui
https://ropensci.org/usecases/occurrences_oaks.html 
Quizá podamos utilizarlo como ejemplo o alguno similar. No sé, que te parece? @ibartomeus

**Comment by CarlosLaraR** [comment]
Hola @ibartomeus y cia,

Muy chula la nota. Estuve leyéndola y aplicando el código. Para mí ha sido muy útil y como soy el siguiente (o casi) en la lista de contribuciones me ha venido muy bien para ver el estilo que le queremos dar a las notas.
He probado a representar los datos de Silene ciliata (mi especie favorita, ya ves que soy muy obediente) y contenían errores claros.  Por ejemplo datos en el mar o fuera del rango ecológico de la especie. Nada fuera de lo común ya que la calidad de los datos muchas veces no es la ideal. En su día cuando descargué los datos del gbif tuve que hacer mucho trabajo de limpieza de datos.  ¿Existen herramientas en R u otras plataformas que faciliten este trabajo? Creo que podría ser un buen aporte para la nota. Quizás simplemente una pequeña mención a ese tema.

Sólo una idea,

Un saludo,

**Comment by ajpelu** [comment]
Hola @CarlosLaraR @ibartomeus 

Yo conozco este [paper](http://onlinelibrary.wiley.com/doi/10.1111/ecog.02118/full) donde exponen un paquete de R que ayuda a evaluar la calidad de los datos de GBIF. Espero sea últil. 

Me parece bien lo que propones de incorporarlo a la nota. 

Abrazos

**Comment by Pakillo** [comment]
Genial. Gracias @CarlosLaraR por la revisión! 

Los de rOpenSci están desarrollando scrubr (https://github.com/ropensci/scrubr)m precisamente para eso: limpiar datos de ocurrencias. El paquete biogeo también está muy bien. Estoy de acuerdo en que es buena idea mencionarlos en la nota! Aunque aún hay mucho trabajo por hacer en cuanto a desarrollo de tools para limpieza y control de calidad de los datos...

**Comment by ibartomeus** [comment]
Gracias a los dos, buen punto, lo añado!

**Comment by ibartomeus** [comment]
Gracias a todos, cierro el issue, y envio a publicar!
